# Generated by Django 5.1.2 on 2025-04-10 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PM', '0006_remove_task_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bugs',
            fields=[
                ('bug_id', models.AutoField(primary_key=True, serialize=False)),
                ('bug_title', models.CharField(max_length=255)),
                ('bug_description', models.TextField()),
                ('bug_priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=50)),
                ('bug_severity', models.CharField(choices=[('Minor', 'Minor'), ('Major', 'Major'), ('Critical', 'Critical')], max_length=50)),
                ('bug_image', models.ImageField(blank=True, null=True, upload_to='bug_images/')),
                ('bug_date', models.DateField()),
                ('related_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bugs', to='PM.task')),
            ],
        ),
    ]
