# Generated by Django 5.1.2 on 2025-04-05 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_status',
        ),
    ]
