# Generated by Django 5.1.2 on 2025-04-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_project_is_completed_project_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeuser',
            name='employee_qualification',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
