# Generated by Django 5.1.2 on 2025-04-08 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_start_date',
            field=models.DateField(null=True),
        ),
    ]
