# Generated by Django 5.1.2 on 2025-04-09 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PM', '0005_task_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
